### ISSUE TITLE
Binary search failed

### ISSUE THREAD

**Issue by makdisse** [facebookresearch/encodec#85]
## 🐛 Bug Report

When you encode in one hardware and try to decode on a different machine it will fail to decode even using the same versions for all libraries.

## To Reproduce

1. Encode a file on a machine that has no GPU or ir a notebook (I'm not sure what hardware difference is causing the error TBH)
2. Try to decode the file on a machine that has a GPU or is a desktop (must be totally different hardware)

## Expected behavior

It should decode as both machines are using encodec 0.1.1 and torch 2.4.1 and python 3.9.13

## Actual Behavior

The decoding fails with this error:

```
PS E:\voice_notes\decode> python.exe -m encodec .\20241009121035.wav.ecdc
Traceback (most recent call last):
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\__main__.py", line 123, in <module>
    main()
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\__main__.py", line 92, in main
    out, out_sample_rate = decompress(args.input.read_bytes())
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\compress.py", line 185, in decompress
    return decompress_from_file(fo, device=device)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\compress.py", line 143, in decompress_from_file
    code = decoder.pull(q_cdf)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 255, in pull
    sym, self.low, self.high, self.current = bin_search(0, len(quantized_cdf) - 1)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 250, in bin_search
    return bin_search(mid + 1, high_idx)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 250, in bin_search
    return bin_search(mid + 1, high_idx)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 252, in bin_search
    return bin_search(low_idx, mid - 1)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 252, in bin_search
    return bin_search(low_idx, mid - 1)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 252, in bin_search
    return bin_search(low_idx, mid - 1)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 250, in bin_search
    return bin_search(mid + 1, high_idx)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 250, in bin_search
    return bin_search(mid + 1, high_idx)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 250, in bin_search
    return bin_search(mid + 1, high_idx)
  [Previous line repeated 1 more time]
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 252, in bin_search
    return bin_search(low_idx, mid - 1)
  File "C:\Users\Paulo\scoop\apps\python39\current\lib\site-packages\encodec\quantization\ac.py", line 238, in bin_search
    raise RuntimeError("Binary search failed")
RuntimeError: Binary search failed
```

It has happened multiple times using different machines. I have old encoded files that I am unable to decode on any machine now.

## Your Environment

- Python and PyTorch version: python 3.9.13, torch 2.4.1
- Operating system and version (desktop or mobile): windows 11 on both machines
- Hardware (gpu or cpu, amount of RAM etc.): 
machine A - encoder) 16gb, notebook, Intel(R) Pentium(R) CPU 4405U @ 2.10GHz
machine B - decoder) 48gb, AMD Ryzen 5 3600 6-Core Processor

**Comment by jbrough** [comment]
Exact same issue for all files I have. OSX version caused it I think as I'm on the same M2 machine. 

This is catastrophic. :(

For a moment I thought they'd switched the weights.

**Comment by jbrough** [comment]
I have put months of work into an art project that used a form of encodec stenography and the whole concept was that they would be indelible forever Ian the visual spectrum as long as the model weights still existed in human knowledge. I guess there’s a beauty to this NOT being the case - as a format it now seems it’s more vulnerable to corruption than unpowered SSDs stored in a clay oven. I should have kept an eye on the issues although the most significant investment in this was made nearly a year ago so that wouldn’t have helped me anyway.

I’m interested in figuring out what has happened and if it can be made stable.

Would it be possible to create a calibration process if this is due to a consistent drift in calculations (the model is completely deterministic in terms of byte output when all things are equal - repeated encodings will give the same results). 

It’s not CPU vs GPU per se - tracks recorded on the same M2 are now lost on the same M2.

My hunch is its software and floating point arithmetic (this could also manifest itself as a difference on cou vs gpu or different hardware though of course). I can’t help thinking a requirements file that locked versions might have helped make this reversible. That said i don’t remember changing my Python env since I last encoded the now undecodable files in the summer and I tried a version matrix of different torch / python versions etc yesterday (but not dependencies like numpy - a very likely culprit - directly) with no luck. 

So my suspicion is that it’s related to operating system software, in my case. I have upgraded osx on my Mac several times…

Going to investigate more. It could even be solar activity during the summer subtly effecting the vector quantisation…. I may tell myself that as it makes it sounds better and makes it easier to bear the loss of such an amount of time and money that was put into my encodec art/music project 😭.

When quantisation becomes quantum in nature… 

Ps - wondering if the C port may be more stable due to being able to better lock in dependencies but I don’t think it supports 48hrs.
